services:
  php-app:
    build:
      context: docker/php-app
    depends_on:
      - mysql
      - redis
      - minio-create-buckets
    volumes:
      - ./app:/var/www/html
    environment:
      CACHE_SESSION_URL: "redis://redis"
      CACHE_SEQUENCE_URL: "redis://redis"
      WEB_DOCUMENT_ROOT: "/app/webroot"
      DEBUG: "true"
      DATABASE_URL: "mysql://tutorials:sup3r_s3cr3t@mysql/tutorials"
      XDEBUG_CONFIG: "client_host=host.docker.internal"
      XDEBUG_MODE: "develop,debug"
      XDEBUG_SESSION: 1
      PHP_IDE_CONFIG: "serverName=tutorial"
    ports:
      - "80:80"

  mysql:
    image: mysql:8.0
    volumes:
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "sup3r_s3cr3t"
      MYSQL_USER: "tutorials"
      MYSQL_PASSWORD: "sup3r_s3cr3t"
      MYSQL_DATABASE: "tutorials"
    command: mysqld --character-set-server=utf8 --init-connect='SET NAMES UTF8;'
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2.7

  node:
    image: node:20.12.2
    volumes:
      - ./:/src
      - /src/frontend/node_modules
    # Since the volume is per container, leave it running.
    tty: true
    working_dir: /src/frontend

  minio:
    image: minio/minio:RELEASE.2022-07-08T00-05-23Z
    environment:
      MINIO_ROOT_USER: AKIAEXAMPLEEXAMPLEEX
      MINIO_ROOT_PASSWORD: EXAMPLESECRETKEY/EXAMPLESECRETKEY/EXAMPL
    ports:
        - "9000:9000"
        - "9001:9001"
    volumes:
      - minio-data:/data
    command: minio server --console-address ":9001" /data

  minio-create-buckets:
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
      until (/usr/bin/mc config host add myminio http://minio:9000 AKIAEXAMPLEEXAMPLEEX EXAMPLESECRETKEY/EXAMPLESECRETKEY/EXAMPL) do echo '...waiting...' && sleep 1; done;
      /usr/bin/mc mb myminio/public;
      /usr/bin/mc policy set public myminio/public;
      /usr/bin/mc mb myminio/private;
      /usr/bin/mc policy set none myminio/private;
      /usr/bin/mc mb myminio/test-private;
      /usr/bin/mc policy set none myminio/test-private;
      exit 0;
      "

volumes:
  minio-data:
  mysql-data:
