const LOCALE_DATE_FORMAT = "YYYY/MM/DD (ddd)";
const LOCALE_TIME_FORMAT = "HH:mm";
const LOCALE_DATETIME_FORMAT = `${LOCALE_DATE_FORMAT} ${LOCALE_TIME_FORMAT}`;

export { LOCALE_DATE_FORMAT, LOCALE_TIME_FORMAT, LOCALE_DATETIME_FORMAT };
